<template><div><h1 id="tsconfig-json" tabindex="-1"><a class="header-anchor" href="#tsconfig-json"><span>tsconfig.json</span></a></h1>
<div class="language-json line-numbers-mode" data-highlighter="prismjs" data-ext="json" data-title="json"><pre v-pre class="language-json"><code><span class="line"><span class="token punctuation">{</span></span>
<span class="line">  <span class="token property">"compilerOptions"</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token property">"target"</span><span class="token operator">:</span> <span class="token string">"esnext"</span><span class="token punctuation">,</span> <span class="token comment">//最终编译的类型</span></span>
<span class="line">    <span class="token property">"lib"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token comment">//影响编译环境</span></span>
<span class="line">        <span class="token string">"esnext"</span><span class="token punctuation">,</span> <span class="token comment">//es版本-更新的版本</span></span>
<span class="line">        <span class="token string">"dom"</span><span class="token punctuation">,</span> <span class="token comment">//dom环境不进行报错，例如使用document</span></span>
<span class="line">        <span class="token string">"dom.iterable"</span><span class="token punctuation">,</span> <span class="token comment">//有些dom环境的数字没有迭代器，开启该库环境后，不进行报错</span></span>
<span class="line">        <span class="token string">"scripthost"</span></span>
<span class="line">        <span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token property">"downlevelIteration"</span><span class="token operator">:</span><span class="token boolean">true</span><span class="token punctuation">,</span><span class="token comment">//支持迭代器</span></span>
<span class="line">    <span class="token property">"allowJs"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token comment">//是否运行ts与js交互，默认为不允许</span></span>
<span class="line">    <span class="token property">"skipLibCheck"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span><span class="token comment">//是否跳过对声明文件的检查</span></span>
<span class="line">    <span class="token property">"strict"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span><span class="token comment">//是否严格检查。开启后开启所有检查</span></span>
<span class="line">    <span class="token property">"strictNullChecks"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span><span class="token comment">//是否检查空类型</span></span>
<span class="line">    <span class="token property">"strictPropertyInitialization"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span><span class="token comment">//是否检查类型初始化</span></span>
<span class="line">    <span class="token property">"forceConsistentCasingInFileNames"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span><span class="token comment">//是否不允许大小写不一致的文件引用，true区分大小写</span></span>
<span class="line">    <span class="token property">"module"</span><span class="token operator">:</span> <span class="token string">"esnext"</span><span class="token punctuation">,</span><span class="token comment">//模块化时使用哪个模块化标准。webpack->ts>js->babel->最终的结果，该选项影响ts->js的过程</span></span>
<span class="line">    <span class="token property">"moduleResolution"</span><span class="token operator">:</span> <span class="token string">"node"</span><span class="token punctuation">,</span><span class="token comment">//设置解析模块的模式,使用什么方式解析模块，默认寻找index文件</span></span>
<span class="line">    <span class="token property">"resolveJsonModule"</span><span class="token operator">:</span> <span class="token string">"preserve"</span><span class="token punctuation">,</span><span class="token comment">//是否运行解析json模块，写好的json文件是否允许在ts文件中导入</span></span>
<span class="line">    <span class="token property">"isolatedModules"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span><span class="token comment">//是否一个文件当成一个模块，开启后每一个文件都应该有import/export</span></span>
<span class="line">    <span class="token property">"noImplicitUseStrict"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span><span class="token comment">//编译结果中不包含“use Strict”</span></span>
<span class="line">    <span class="token property">"removeComments"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span><span class="token comment">//编译结果中移除注释</span></span>
<span class="line">    <span class="token property">"noEmitOnError"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span><span class="token comment">//编译错误时不生成编译结果</span></span>
<span class="line">    <span class="token property">"esModuleInterop"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span><span class="token comment">//是否运行commonJs的模块化标准与ES6的模块化标准来进行交互，影响编译结果，在结果中生成辅助函数。</span></span>
<span class="line">    <span class="token property">"allowSyntheticDefaultImports"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span><span class="token comment">//是否开启默认导入的类型检查。开启esModuleInterop即不用开启该配置</span></span>
<span class="line">    <span class="token property">"noEmit"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span><span class="token comment">//不生成js文件，直接放入内存，直接编译后交给下一步处理</span></span>
<span class="line">    <span class="token property">"jsx"</span><span class="token operator">:</span> <span class="token string">"preserve"</span><span class="token punctuation">,</span><span class="token comment">//解析jsx的方式。preserve:[&lt;div />]->[&lt;div />]->[.jsx]、react:[&lt;div />]->[React.createElement("div")]->[.js]react-native:[&lt;div />]->[&lt;div />]->[.js]</span></span>
<span class="line"></span>
<span class="line">    <span class="token property">"strictPropertyInitialization"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span><span class="token comment">//严格检查 属性初始化，检查构造函数与属性默认值</span></span>
<span class="line">    <span class="token property">"typeRoots"</span><span class="token operator">:</span><span class="token punctuation">[</span><span class="token string">"./types"</span><span class="token punctuation">]</span><span class="token punctuation">,</span><span class="token comment">// 声明文件位置</span></span>
<span class="line">    <span class="token property">"declaration"</span><span class="token operator">:</span><span class="token boolean">true</span><span class="token punctuation">,</span><span class="token comment">//发布后生成声明文件</span></span>
<span class="line">    </span>
<span class="line">    <span class="token property">"importHelpers"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token property">"useDefineForClassFields"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token property">"sourceMap"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token property">"baseUrl"</span><span class="token operator">:</span> <span class="token string">"."</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token property">"types"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"webpack-env"</span><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token property">"paths"</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token property">"@/*"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"src/*"</span><span class="token punctuation">]</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">    </span>
<span class="line">    <span class="token property">"typeRoots"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"node_modules/@types"</span><span class="token punctuation">,</span> <span class="token string">"src/types"</span><span class="token punctuation">]</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token property">"include"</span><span class="token operator">:</span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string">"src/**/*.ts"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"src/**/*.tsx"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"src/**/*.vue"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"tests/**/*.ts"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"tests/**/*.tsx"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"src/types/*.d.ts"</span><span class="token punctuation">,</span> </span>
<span class="line">    <span class="token string">"src/types/Global.d.ts"</span></span>
<span class="line">  <span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token property">"exclude"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"node_modules"</span><span class="token punctuation">]</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


